"use strict";

module.exports = function(grunt) {

  require("load-grunt-tasks")(grunt);

  grunt.initConfig({
    less: {
      style: {
        files: {
          "css/style.css": "less/style.less"
        }
      }
    },

    postcss: {
      style: {
        options: {
          processors: [
            require("autoprefixer")({browsers: [
              "last 2 versions"
            ]})
          ]
        },
        src: "css/*.css"
      }
    },

    browserSync: {
      server: {
        bsFiles: {
          src: [
            "*.html",
            "css/*.css"
          ]
        },
        options: {
          server: ".",
          watchTask: true,
          notify: false,
          open: true,
          cors: true,
          ui: false
        }
      }
    },

    watch: {
      style: {
        files: ["**/*.less"],
        tasks: ["less", "postcss"]
      }
      // html_js: {
      //   files: ["*.html", "js/**"],
      //   tasks: ["copy"]
      // }
    },

    csso: {
      style: {
        options: {
          report: "gzip"
        },
        files: {
          "css/style.min.css" : ["css/style.css"]
        }
      }
    },

    // imagemin: {
    //   images: {
    //     options: {
    //       opitimizationLabel: 3
    //     },
    //     files: [{
    //       expand: true,
    //       src: ["build/img/**/*{png,jpg,gif}"]
    //     }]
    //   }
    // },

    // svgmin: {
    //   symbols: {
    //     files: [{
    //       expand: true,
    //       src: ["build/img/icons/*.svg"]
    //     }]
    //   }
    // },

    //  svgstore: {
    //    options: {
    //      svg: {
    //        style: "display: none"
    //      }
    //    },
    //    symbols: {
    //      files: {
    //        "build/img/symbols.svg": ["img/icons/*.svg"]
    //      }
    //    }
    //  },

  //   copy: {
  //     build: {
  //       files: [{
  //         expand: true,
  //         src: [
  //           "fonts/**/*.{woff, woff2}",
  //           "img/**",
  //           "js/**",
  //           "*.html"
  //         ],
  //         dest: "build"
  //       }]
  //     }
  //   },
  //
  //   clean: {
  //     build: ["build"]
  //   },
  //
  //   'gh-pages': {
  //     options: {
  //       base: 'build' ,
  //       message: 'Generated by grunt gh-pages'
  //     },
  //       src: ['**/*']
  //   }
  });

  // grunt.registerTask ('deploy', ['gh-pages']);

  grunt.registerTask("serve", ["browserSync", "watch"]);
  // grunt.registerTask("symbols", ["svgmin", "svgstore"]);
  grunt.registerTask("build", [
    // "clean",
    // "copy",
    "less",
    "postcss",
    "csso"
    // "symbols",
    // "imagemin"
  ]);
};
